### ISSUE TITLE
Bump in Fedora

### ISSUE THREAD

**Issue by puiterwijk** [fedora-iot/zezere#2]
/packit propose-update

**Comment by jpopelka** [comment]
> Account is not whitelisted!

Looks like a bug, you should have been whitelisted automatically since your github login matches your Fedora FAS. I'll take a look.

**Comment by jpopelka** [comment]
I've just approved also `puiterwijk` to work-around the packit-service/packit-service#308 and will investigate it later.

**Comment by puiterwijk** [comment]
@jpopelka Thanks!

**Comment by dhodovsk** [comment]
This seems to be be related to https://stackoverflow.com/questions/26140372/cannot-get-releases-for-a-repo-with-the-github-api

**Comment by puiterwijk** [comment]
(For the record: I now actually created a full GitHub release for v0.2)

**Comment by puiterwijk** [comment]
Just pushed as `0.2` without `v` prefix.

**Comment by dhodovsk** [comment]
Related issue: https://github.com/packit-service/packit-service/issues/423

**Comment by puiterwijk** [comment]
Looks like it now automatically determines it and files issues if it failed.
