### ISSUE TITLE
Ability to provision pre-canned images

### ISSUE THREAD

**Issue by nullr0ute** [fedora-iot/zezere#29]
Images for cloud and devices like the Raspberry Pi often deploy a pre generated image. The ability to be able to auto provision users/keys and other post install related things is useful.

So being able to boot a device and have ignition retrieve a config and auto provision.

**Comment by puiterwijk** [comment]
This comes down to:
1. Make sure Ignition retrieves a URL that includes the devices' MAC address (or other ID).
2. Add device auto-registration to the Ignition config retrieval URL like dyngrubcfg (right now it errors with a 404).

An idea for #1 would be to ship a static Ignition config that drops a new script, and systemd unit that calls it, that would re-run ignition with the correct device ID.
